name = "ExpressWorkflowMaker"
uuid = "e7e42fff-c592-4d8a-934a-030a060c623e"
authors = ["Reno <singularitti@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
